#lang scheme

;; Using the substituion model, illustrate the process generated by each procedure in evaluating (+ 4 5). Are these processes iterative or recursive?

;; 1

(define (+ a b)
  (if (= a 0)
	b
	(inc (+ (dec a) b))))

;; This process generated above is recursive because the interpreter must store deffered operations ( (+ (dec a) b) ) before it evaluates (inc).

;; 2

(define (+ a b)
  (if (= a 0)
	b
	(+ (dec a) (inc b))))

;; This process is iterative because the interpreter does not have to defer any operations
